CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('USER', 'ADMIN')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS documents (
  id SERIAL PRIMARY KEY,
  tracking_code VARCHAR(20) NOT NULL UNIQUE,
  user_id INTEGER NOT NULL REFERENCES users (id),
  subject VARCHAR(200) NOT NULL,
  document_type VARCHAR(80) NOT NULL,
  description TEXT,
  file_path VARCHAR(255),
  status VARCHAR(20) NOT NULL CHECK (status IN ('RECIBIDO', 'EN_REVISION', 'ATENDIDO', 'RECHAZADO')),
  observation TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS status_history (
  id SERIAL PRIMARY KEY,
  document_id INTEGER NOT NULL REFERENCES documents (id),
  status VARCHAR(20) NOT NULL CHECK (status IN ('RECIBIDO', 'EN_REVISION', 'ATENDIDO', 'RECHAZADO')),
  observation TEXT,
  changed_by INTEGER REFERENCES users (id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users (id),
  action VARCHAR(80) NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
