-- Los datos iniciales de usuario no se insertan aquí.
-- La contraseña no debe quedar en texto plano en el repositorio.
-- Para crear el administrador de desarrollo:
--   cd backend
--   definir ADMIN_PASSWORD en .env
--   npm run seed:admin
--
-- Para cargar datos de demostración reconstruibles:
--   definir ADMIN_PASSWORD y DEMO_USER_PASSWORD en backend/.env
--   cd backend
--   npm run seed:demo
--
-- El script crea un administrador, dos ciudadanos y cuatro documentos sin
-- archivos asociados. Los documentos incluyen estados e historial para la
-- exposición, sin depender de PDF existentes.
